CREATE TABLE IF NOT EXISTS cars_data (
    "Scraping time" REAL,
    Name TEXT,
    Prix REAL,
    Location TEXT,
    Type TEXT,
    Secteur TEXT,
    "Première main" TEXT,
    "Nombre de portes" INTEGER,
    Modèle TEXT,
    Kilométrage REAL,
    Marque TEXT,
    "Année-Modèle" INTEGER,
    État TEXT,
    Origine TEXT);
